[platformio]
default_envs = esp32-2432S028R

[env:esp32-2432S028R]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
extra_scripts = pre:tools/patch_ubitcoin.py
lib_deps =
  lvgl/lvgl@8.4.0
  bodmer/TFT_eSPI@2.5.43
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#f956c5d8ce3bf39169c7378416b89e7cfe70a034
  https://github.com/micro-bitcoin/uBitcoin.git#877542fdc16319dd92a7d2a679ea9dacce474bd2
build_flags =
  -D USER_SETUP_LOADED=1
  -D ILI9341_2_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=21
  -D TFT_BACKLIGHT_ON=HIGH
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=16000000
  -D LV_CONF_INCLUDE_SIMPLE
  -I include
  -D CORE_DEBUG_LEVEL=0
lib_ldf_mode = deep+
