[platformio]
default_envs = waveshare-p4
src_dir = main

[env:waveshare-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-p4_r3
framework = espidf
monitor_speed = 115200
extra_scripts = post:tools/image_revision.py
board_upload.flash_size = 32MB
board_build.partitions = partitions.csv
board_build.f_flash = 80000000L
board_build.f_psram = 250000000L
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults

[env:waveshare-p4-rev1]
extends = env:waveshare-p4
board = esp32-p4
board_build.f_psram = 200000000L
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.rev1.defaults"
