#pragma once
#define LV_CONF_H
#define LV_COLOR_DEPTH 16
#define LV_FONT_MONTSERRAT_20 1
#define LV_USE_OS 0
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CUSTOM
#define LV_MEM_SIZE (2 * 1024 * 1024)
#define LV_USE_LOG 0
#define LV_USE_SYSMON 0
#define LV_USE_QRCODE 1
#define LV_USE_SNAPSHOT 1
#define LV_USE_THORVG_INTERNAL 0
#define LV_USE_THORVG_EXTERNAL 0
#define LV_BUILD_EXAMPLES 0
#define LV_BUILD_DEMOS 0
