#pragma once

#define AURORA_CYD_FIRMWARE_VERSION "1.9.7"
#define AURORA_P4_FIRMWARE_VERSION "2.0.3"

#if defined(AURORA_BOARD_P4)
#define AURORA_FIRMWARE_VERSION AURORA_P4_FIRMWARE_VERSION
#else
#define AURORA_FIRMWARE_VERSION AURORA_CYD_FIRMWARE_VERSION
#endif
